---
name: Continuous integration

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20, 22]
        steps:
            - name: Setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: Europe/Berlin
            - uses: actions/checkout@v5
            - name: Use Node.js v${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm clean-install
            - name: Compile source code
              run: npm run compile
            - name: Lint source code
              run: npm run lint
            - name: Run unit tests
              run: npm run test:unit:coverage
              env:
                  FORCE_COLOR: 1
            - name: Check for copy and paste
              run: npm run copy:paste:detection
            - name: Run integration tests
              run: npm run test:integration
              env:
                  FORCE_COLOR: 1
